%
% Graphical User Interface for visualizing all 2-dim data in an HDF5
% "CRPP standard format result file".
%

function GUI_vis2d


global editHandle1 editHandle2 editHandle3 editHandle4 editHandle5...
       editHandle6 editHandle7 editHandle8 editHandle9 ...
       editHandle10 editHandle11 ...
       figureHandle1 figureHandle2 figureHandle3 figureHandle4 ...
       figureHandle5 figureHandle6 ...	 
       listboxHandle1 listboxHandle2 ...
       checkboxHandle1 checkboxHandle2 checkboxHandle3 ...
       checkboxHandle4 checkboxHandle5 ...
       popupmenuHandle1 popupmenuHandle2 ... 
       popupmenuHandle3 popupmenuHandle4 ...
       axesHandle1 axesHandle2 axesHandle3 axesHandle4...
       axesHandle5 axesHandle6 ...
       sliderHandle1 ...
       buttonHandle1 buttonHandle2 buttonHandle3

global nx x_min x_max  xm ...
       ny y_min y_max  ym ...
       z_min z_max ...
       zx_min zx_max ...
       zy_min zy_max ...
       zxint_min zxint_max ...
       zyint_min zyint_max ...
       nx_skip ny_skip ...
       n_frames t_initial t_final tm i_frame time newY ...
       n_skip dt_pause ...
       field field_it ...
       plot_2dim plot_xcut plot_ycut ...
       plot_style shading_style ...
       x_text y_text z_text title_text...
       x_cut y_cut i_x_cut i_y_cut ...
       x_scale y_scale	   

%--- Initializing

nx_skip = 1;
ny_skip = 1;
n_skip = 1;
dt_pause = 0.25;
plot_style = 'pcolor';
shading_style = 'flat';
plot_2dim = 0;
plot_xcut = 0;
plot_ycut = 0;
x_scale = 'lin';
y_scale = 'lin';
i_frame = 1;
time = t_initial;
newY = 0.;
dir_path = pwd;

%-- FILE --------------------------------------------------------------
%----------------------------------------------------------------------

figureHandle1 = figure;

uicontrol('Style', 'frame', ...
	  'Units', 'normalized', ...
	  'Position', [.02 .52 .6 .45])

uicontrol('Style', 'text', ...
	  'String', 'DATA',...
	  'Units', 'normalized', ...
	  'FontSize', [18], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [1 0 0], ...	
	  'Position', [.05 .92 .2 .07])

uicontrol('Style', 'text', ...
	  'String', 'Directory:',...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.05 .85 .15 .07])

editHandle1 = uicontrol('Style', 'Edit', ...
	  'String', dir_path, ...
          'Callback', 'GUI_action2d change_dir', ...
	  'Units', 'normalized', ...
	  'Position', [.2 .86 .4 .07]);

uicontrol('Style', 'text', ...
	  'String', 'Files:',...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.05 .76 .1 .07])

listboxHandle1 = uicontrol('Style', 'listbox', ...
	  'String', sort(str2cell(['.. ', ls(dir_path)])),...
	  'Callback', 'GUI_action2d read_file', ...	
	  'Units', 'normalized', ...
	  'Position', [.05 .54 .3 .25]);

uicontrol('Style', 'text', ...
	  'String', 'Variables:',...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.4 .76 .15 .07])

listboxHandle2 = uicontrol('Style', 'listbox', ...
	  'Callback', 'GUI_action2d load_variable', ...	
	  'Units', 'normalized', ...
	  'Position', [.4 .54 .2 .25]);

%-- PLOT --------------------------------------------------------------
%----------------------------------------------------------------------

%-- 2-Dim

uicontrol('Style', 'frame', ...
	  'Units', 'normalized', ...
	  'Position', [.02 .02 .97 .45])

uicontrol('Style', 'text', ...
	  'String', 'PLOT',...
	  'FontSize', [18], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 1 0], ...
	  'Units', 'normalized', ...
	  'Position', [.05 .42 .2 .07])

checkboxHandle1 = uicontrol('Style', 'checkbox', ...
	  'String', '2-Dim',...
	  'Enable', 'off', ...
	  'Callback', 'GUI_action2d plot_2dim', ...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.04 .29 .2 .1]);

uicontrol('Style', 'text', ...
	  'String', '2-D plot style',...
	  'Units', 'normalized', ...
	  'Position', [.22 .37 .16 .05])

popupmenuHandle1 = uicontrol('Style', 'popupmenu', ...
	  	       'String', {'pcolor';'surf'; 'mesh'; 'contour'},...
	  	       'Enable', 'off', ...
		       'Callback', 'GUI_action2d read_plot_style', ...
   	               'Units', 'normalized', ...
	  	       'Position', [.22 .3 .16 .07]);

uicontrol('Style', 'text', ...
	  'String', 'shading',...
	  'Units', 'normalized', ...
	  'Position', [.39 .37 .16 .05])

popupmenuHandle2 = uicontrol('Style', 'popupmenu', ...
	  	        'String', {'flat'; 'interp'; 'faceted'},...
	               'Enable', 'off', ...
	  	     'Callback', 'GUI_action2d read_shading_style', ...
   	               'Units', 'normalized', ...
	  	       'Position', [.39 .3 .16 .07]);

uicontrol('Style', 'text', ...
	  'String', 'X',...
	  'Units', 'normalized', ...
	  'Position', [.58 .35 .05 .05])

uicontrol('Style', 'text', ...
	  'String', 'Y',...
	  'Units', 'normalized', ...
	  'Position', [.58 .27 .05 .05])


uicontrol('Style', 'text', ...
	  'String', 'limits',...
	  'Units', 'normalized', ...
	  'Position', [.65 .40 .1 .05])


editHandle8 = uicontrol('Style', 'Edit', ...
	  'String', '',...
	  'Enable', 'off', ...
          'Callback', 'GUI_action2d read_XLim', ...
	  'Units', 'normalized', ...
	  'Position', [.64 .35 .12 .06]);


editHandle9 = uicontrol('Style', 'Edit', ...
	  'String', '',...
	  'Enable', 'off', ...
          'Callback', 'GUI_action2d read_YLim', ...
	  'Units', 'normalized', ...
	  'Position', [.64 .28 .12 .06]);

uicontrol('Style', 'text', ...
	  'String', 'skip grid pts',...
	  'Units', 'normalized', ...
	  'Position', [.80 .40 .15 .05])

editHandle10 = uicontrol('Style', 'Edit', ...
	  'String', '1',...
	  'Enable', 'off', ...
          'Callback', 'GUI_action2d read_xgrid_skip', ...
	  'Units', 'normalized', ...
	  'Position', [.83 .35 .10 .06]);


editHandle11 = uicontrol('Style', 'Edit', ...
	  'String', '1',...
	  'Enable', 'off', ...
          'Callback', 'GUI_action2d read_ygrid_skip', ...
	  'Units', 'normalized', ...
	  'Position', [.83 .28 .10 .06]);

%-- X-cut

checkboxHandle2 = uicontrol('Style', 'checkbox', ...
	  'String', 'X-Cut',...
	  'Enable', 'off', ...
	  'Callback', 'GUI_action2d plot_xcut', ...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.04 .17 .2 .1]);

uicontrol('Style', 'text', ...
	  'String', 'at position',...
	  'Units', 'normalized', ...
	  'Position', [.22 .19 .16 .05])

editHandle2 = uicontrol('Style', 'Edit', ...
	  'String', '',...
	  'Enable', 'off', ...
          'Callback', 'GUI_action2d read_xcut_position', ...
	  'Units', 'normalized', ...
	  'Position', [.39 .18 .1 .07]);

%-- Y-cut

checkboxHandle3 = uicontrol('Style', 'checkbox', ...
	  'String', 'Y-Cut',...
	  'Enable', 'off', ...
	  'Callback', 'GUI_action2d plot_ycut', ...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.04 .05 .2 .1]);

uicontrol('Style', 'text', ...
	  'String', 'at position',...
	  'Units', 'normalized', ...
	  'Position', [.22 .07 .16 .05])

editHandle3 = uicontrol('Style', 'Edit', ...
	  'String', '',...
	  'Enable', 'off', ...
          'Callback', 'GUI_action2d read_ycut_position', ...
	  'Units', 'normalized', ...
	  'Position', [.39 .06 .1 .07]);

%-- X-Integrated

checkboxHandle4 = uicontrol('Style', 'checkbox', ...
	  'String', 'X-Int',...
	  'Enable', 'off', ...
	  'Callback', 'GUI_action2d plot_xint', ...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.59 .17 .2 .1]);

%-- Y-Integrated

checkboxHandle5 = uicontrol('Style', 'checkbox', ...
	  'String', 'Y-Int',...
	  'Enable', 'off', ...
	  'Callback', 'GUI_action2d plot_yint', ...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.59 .05 .2 .1]);

popupmenuHandle3 = uicontrol('Style', 'popupmenu', ...
	  	       'String', {'lin', 'log'},...
	  	       'Enable', 'off', ...
		       'Callback', 'GUI_action2d read_x_scale', ...
   	               'Units', 'normalized', ...
	  	       'Position', [.79 .18 .1 .07]);

popupmenuHandle4 = uicontrol('Style', 'popupmenu', ...
	  	       'String', {'lin', 'log'},...
	  	       'Enable', 'off', ...
		       'Callback', 'GUI_action2d read_y_scale', ...
   	               'Units', 'normalized', ...
	  	       'Position', [.79 .06 .1 .07]);

%-- TIME --------------------------------------------------------------
%----------------------------------------------------------------------

uicontrol('Style', 'frame', ...
	  'Units', 'normalized', ...
	  'Position', [.64 .52 .34 .45])

uicontrol('Style', 'text', ...
	  'String', 'TIME',...
	  'FontSize', [18], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 1], ...
	  'Units', 'normalized', ...
	  'Position', [.73 .92 .16 .07])

sliderHandle1 = uicontrol('Style', 'slider', ...
    	  	  'Enable', 'off', ...
  		  'Callback', 'GUI_action2d convert_slider',... 
		  'Min', 0, 'Max', 1, ...
		  'Interruptible', 'off', ...
		  'BusyAction', 'cancel', ...
		  'Units', 'normalized', ...
	  	  'Position', [.68 .88 .27 .05]);

buttonHandle1 = uicontrol('Style', 'pushbutton', ...
		          'String', 'FWD', ...
      	  	  	  'Enable', 'off', ...
	  		  'Callback', 'GUI_action2d run_forward', ... 
			  'Interruptible', 'on', ...
			  'Units', 'normalized', ...
	  		  'Position', [.86 .8 .09 .08]);

buttonHandle2 = uicontrol('Style', 'pushbutton', ...
		          'String', 'BKD', ...
      	  	  	  'Enable', 'off', ...
	  		  'Callback', 'GUI_action2d run_backward', ... 
			  'Units', 'normalized', ...
			  'Interruptible', 'on', ...
			  'Position', [.68 .8 .09 .08]);

buttonHandle3 = uicontrol('Style', 'pushbutton', ...
		          'String', 'STOP', ...
			  'UserData', [0], ...
      	  	  	  'Enable', 'off', ...
  			  'Callback', 'GUI_action2d run_stop', ...
			  'Units', 'normalized', ...
	  		  'Position', [.77 .8 .09 .08]);

uicontrol('Style', 'text', ...
	  'String', 'skip :',...
	  'Units', 'normalized', ...
	  'Position', [.65 .73 .07 .05])

editHandle4 = uicontrol('Style', 'Edit', ...
	                'String', '1',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action2d read_skip', ...
               	        'Units', 'normalized', ...
	                'Position', [.72 .73 .07 .07]);

uicontrol('Style', 'text', ...
	  'String', 'pause:',...
	  'Units', 'normalized', ...
	  'Position', [.8 .73 .08 .05])

editHandle5 = uicontrol('Style', 'Edit', ...
	                'String', '0.25',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action2d read_pause', ...
               	        'Units', 'normalized', ...
	                'Position', [.88 .73 .08 .07]);

uicontrol('Style', 'text', ...
	  'String', 'frame #',...
	  'Units', 'normalized', ...
	  'Position', [.65 .66 .12 .05])

editHandle6 = uicontrol('Style', 'Edit', ...
	                'String', '',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action2d convert_frame', ...
               	        'Units', 'normalized', ...
	                'Position', [.78 .65 .1 .07]);

uicontrol('Style', 'text', ...
	  'String', 'Time ',...
	  'Units', 'normalized', ...
	  'Position', [.65 .58 .12 .05])

editHandle7 = uicontrol('Style', 'Edit', ...
	                'String', '',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action2d convert_time', ...
	                'Units', 'normalized', ...
	                'Position', [.78 .57 .1 .07]);

%----------------------------------------------------------------------
%----------------------------------------------------------------------


function cstr = str2cell(string)

%--- converts a string of words to a cell of strings for each word

iname = 0;
while ~isempty(string),
  iname = iname + 1;
  [name, string] = strtok(string);
  cstr(iname) = {name};
  string = deblank(string);
end

%----------------------------------------------------------------------
%----------------------------------------------------------------------

