%
% Graphical User Interface for visualizing all 1-dim data in an HDF5
% "CRPP standard format result file".
%

function GUI_vis1d


global editHandle1d_1 editHandle1d_2 editHandle1d_3...
       editHandle1d_4 editHandle1d_5 ...
       figureHandle1d_1 figureHandle1d_2 ...
       listboxHandle1d_1 listboxHandle1d_2 ...
       sliderHandle1d_1 ...
       buttonHandle1d_1 buttonHandle1d_2 buttonHandle1d_3 buttonHandle1d_4 ... 
       popupmenuHandle1d_1 popupmenuHandle1d_2       

global n_frames_1d t_initial_1d t_final_1d tm_1d ...
       i_frame_1d time_1d newY_1d ...
       n_skip_1d dt_pause_1d ...
       plot_obj n_hor n_ver plot_OK ...
       type_ylim y_scale

%-- INITIALIZE --------------------------------------------------------

dt_pause_1d = 0.25;
n_skip_1d = 1;
type_ylim = 'fixed';
y_scale = 'lin';
dir_path = pwd;

%-- DATA --------------------------------------------------------------
%----------------------------------------------------------------------

figureHandle1d_1 = figure;

uicontrol('Style', 'frame', ...
	  'Units', 'normalized', ...
	  'Position', [.02 .40 .6 .57])

uicontrol('Style', 'text', ...
	  'String', 'DATA',...
	  'Units', 'normalized', ...
	  'FontSize', [18], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [1 0 0], ...	
	  'Position', [.05 .92 .2 .07])

uicontrol('Style', 'text', ...
	  'String', 'Directory:',...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.05 .85 .15 .07])

editHandle1d_1 = uicontrol('Style', 'Edit', ...
	  'String', dir_path,...
          'Callback', 'GUI_action1d change_dir', ...
	  'Units', 'normalized', ...
	  'Position', [.2 .86 .4 .07]);

uicontrol('Style', 'text', ...
	  'String', 'Files:',...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.05 .76 .1 .07])

listboxHandle1d_1 = uicontrol('Style', 'listbox', ...
	  'String', sort(str2cell(['.. ', ls(dir_path)])), ...
	  'Callback', 'GUI_action1d read_file', ...	
	  'Units', 'normalized', ...
	  'Position', [.05 .54 .3 .25]);

uicontrol('Style', 'text', ...
	  'String', 'Variables:',...
	  'FontSize', [12], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 0], ...
	  'Units', 'normalized', ...
	  'Position', [.4 .76 .15 .07])

listboxHandle1d_2 = uicontrol('Style', 'listbox', ...
          'Min', 1, 'Max', 3, ...
	  'Units', 'normalized', ...
	  'Position', [.4 .54 .2 .25]);

buttonHandle1d_4 = uicontrol('Style', 'pushbutton', ...
                             'String', 'Plot', ...
                             'Callback', 'GUI_action1d plot_data', ... 
                             'Units', 'normalized', ...
                             'Position', [.45 .43 .09 .08]);

%-- TIME --------------------------------------------------------------
%----------------------------------------------------------------------

uicontrol('Style', 'frame', ...
	  'Units', 'normalized', ...
	  'Position', [.64 .52 .34 .45])

uicontrol('Style', 'text', ...
	  'String', 'TIME',...
	  'FontSize', [18], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 0 1], ...
	  'Units', 'normalized', ...
	  'Position', [.73 .92 .16 .07])

sliderHandle1d_1 = uicontrol('Style', 'slider', ...
    	  	  'Enable', 'off', ...
  		  'Callback', 'GUI_action1d convert_slider',... 
		  'Min', 0, 'Max', 1, ...
		  'Interruptible', 'off', ...
		  'BusyAction', 'cancel', ...
		  'Units', 'normalized', ...
	  	  'Position', [.68 .88 .27 .05]);

buttonHandle1d_1 = uicontrol('Style', 'pushbutton', ...
		          'String', 'FWD', ...
      	  	  	  'Enable', 'off', ...
	  		  'Callback', 'GUI_action1d run_forward', ... 
			  'Interruptible', 'on', ...
			  'Units', 'normalized', ...
	  		  'Position', [.86 .8 .09 .08]);

buttonHandle1d_2 = uicontrol('Style', 'pushbutton', ...
		          'String', 'BKD', ...
      	  	  	  'Enable', 'off', ...
	  		  'Callback', 'GUI_action1d run_backward', ... 
			  'Units', 'normalized', ...
			  'Interruptible', 'on', ...
	  		  'Position', [.68 .8 .09 .08]);

buttonHandle1d_3 = uicontrol('Style', 'pushbutton', ...
		          'String', 'STOP', ...
			  'UserData', [0], ...
      	  	  	  'Enable', 'off', ...
  			  'Callback', 'GUI_action1d run_stop', ...
			  'Units', 'normalized', ...
	  		  'Position', [.77 .8 .09 .08]);

uicontrol('Style', 'text', ...
	  'String', 'skip :',...
	  'Units', 'normalized', ...
	  'Position', [.65 .73 .07 .05])

editHandle1d_2 = uicontrol('Style', 'Edit', ...
	                'String', '1',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action1d read_skip', ...
               	        'Units', 'normalized', ...
	                'Position', [.72 .73 .07 .07]);

uicontrol('Style', 'text', ...
	  'String', 'pause:',...
	  'Units', 'normalized', ...
	  'Position', [.8 .73 .08 .05])

editHandle1d_3 = uicontrol('Style', 'Edit', ...
	                'String', '0.25',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action1d read_pause', ...
               	        'Units', 'normalized', ...
	                'Position', [.88 .73 .08 .07]);

uicontrol('Style', 'text', ...
	  'String', 'frame #',...
	  'Units', 'normalized', ...
	  'Position', [.65 .66 .12 .05])

editHandle1d_4 = uicontrol('Style', 'Edit', ...
	                'String', '',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action1d convert_frame', ...
               	        'Units', 'normalized', ...
	                'Position', [.78 .65 .1 .07]);

uicontrol('Style', 'text', ...
	  'String', 'Time ',...
	  'Units', 'normalized', ...
	  'Position', [.65 .58 .12 .05])

editHandle1d_5 = uicontrol('Style', 'Edit', ...
	                'String', '',...
      	  	  	'Enable', 'off', ...
	                'Callback', 'GUI_action1d convert_time', ...
	                'Units', 'normalized', ...
	                'Position', [.78 .57 .1 .07]);

%-- AXES --------------------------------------------------------------
%----------------------------------------------------------------------

uicontrol('Style', 'frame', ...
	  'Units', 'normalized', ...
	  'Position', [.64 .27 .34 .20])

uicontrol('Style', 'text', ...
	  'String', 'AXES',...
	  'FontSize', [18], ...
	  'FontWeight', 'bold', ...
	  'ForegroundColor', [0 1 0], ...
	  'Units', 'normalized', ...
	  'Position', [.7 .42 .2 .07])

uicontrol('Style', 'text', ...
	  'String', 'Limits',...
	  'Units', 'normalized', ...
	  'Position', [.69 .37 .07 .05])

popupmenuHandle1d_1 = uicontrol('Style', 'popupmenu', ...
	  	       'String', {'fixed', 'free'},...
	  	       'Enable', 'off', ...
		       'Callback', 'GUI_action1d read_y_limits', ...
   	               'Units', 'normalized', ...
	  	       'Position', [.67 .30 .13 .07]);

uicontrol('Style', 'text', ...
	  'String', 'Scale',...
	  'Units', 'normalized', ...
	  'Position', [.86 .37 .07 .05])

popupmenuHandle1d_2 = uicontrol('Style', 'popupmenu', ...
	  	       'String', {'lin', 'log'},...
	  	       'Enable', 'off', ...
		       'Callback', 'GUI_action1d read_y_scale', ...
   	               'Units', 'normalized', ...
	  	       'Position', [.85 .30 .1 .07]);

%----------------------------------------------------------------------
%----------------------------------------------------------------------

function cstr = str2cell(string)

%--- converts a string of words to a cell of strings for each word

iname = 0;
while ~isempty(string),
  iname = iname + 1;
  [name, string] = strtok(string);
  cstr(iname) = {name};
  string = deblank(string);
end

%----------------------------------------------------------------------
%----------------------------------------------------------------------



